# Generated by Django 4.2.3 on 2023-07-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discovered', models.BooleanField(default=False)),
                ('earthly', models.BooleanField(default=True)),
                ('genres', models.JSONField(default=dict)),
                ('blurb', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('geoDynamics', models.JSONField()),
                ('magicTechnology', models.JSONField()),
                ('imagine', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('lore', models.JSONField(default=list)),
            ],
        ),
    ]
