# Generated by Django 4.2.3 on 2023-07-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='world',
            name='geoDynamics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='world',
            name='img',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='world',
            name='magicTechnology',
            field=models.JSONField(default=dict),
        ),
    ]
