# Generated by Django 4.2.3 on 2023-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_alter_world_description_alter_world_geodynamics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='imgs',
            field=models.JSONField(default=list),
        ),
    ]
