# Generated by Django 4.2.3 on 2023-07-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_world_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='imgs',
            field=models.JSONField(default=dict),
        ),
    ]
