# Generated by Django 4.2.3 on 2023-08-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_alter_world_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='category',
            field=models.CharField(default='', max_length=250),
        ),
    ]
