# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'factory_bot_rails'
include FactoryBot::Syntax::Methods

@chef_1 = create(:chef)
@chef_2 = create(:chef)
@chef_3 = create(:chef)
@chef_4 = create(:chef)
@chef_5 = create(:chef)

@dish_1 = create(:dish, chef: @chef_1)
@dish_2 = create(:dish, chef: @chef_1)
@dish_3 = create(:dish, chef: @chef_1)
@dish_4 = create(:dish, chef: @chef_2)
@dish_5 = create(:dish, chef: @chef_2)
@dish_6 = create(:dish, chef: @chef_2)
@dish_7 = create(:dish, chef: @chef_3)
@dish_8 = create(:dish, chef: @chef_3)
@dish_9 = create(:dish, chef: @chef_3)
@dish_10 = create(:dish, chef: @chef_4)
@dish_11 = create(:dish, chef: @chef_4)
@dish_12 = create(:dish, chef: @chef_4)
@dish_13 = create(:dish, chef: @chef_5)
@dish_14 = create(:dish, chef: @chef_5)
@dish_15 = create(:dish, chef: @chef_5)

@ingredient_1 = create(:ingredient)
@ingredient_2 = create(:ingredient)
@ingredient_3 = create(:ingredient)
@ingredient_4 = create(:ingredient)
@ingredient_5 = create(:ingredient)
@ingredient_6 = create(:ingredient)
@ingredient_7 = create(:ingredient)
@ingredient_8 = create(:ingredient)
@ingredient_9 = create(:ingredient)
@ingredient_10 = create(:ingredient)
@ingredient_11 = create(:ingredient)
@ingredient_12 = create(:ingredient)
@ingredient_13 = create(:ingredient)
@ingredient_14 = create(:ingredient)
@ingredient_15 = create(:ingredient)

@dish_ingredient_1 = create(:dish_ingredient, dish: @dish_1, ingredient: @ingredient_1)
@dish_ingredient_2 = create(:dish_ingredient, dish: @dish_1, ingredient: @ingredient_2)
@dish_ingredient_3 = create(:dish_ingredient, dish: @dish_1, ingredient: @ingredient_3)
@dish_ingredient_4 = create(:dish_ingredient, dish: @dish_2, ingredient: @ingredient_2)
@dish_ingredient_5 = create(:dish_ingredient, dish: @dish_2, ingredient: @ingredient_3)
@dish_ingredient_6 = create(:dish_ingredient, dish: @dish_2, ingredient: @ingredient_4)
@dish_ingredient_7 = create(:dish_ingredient, dish: @dish_3, ingredient: @ingredient_3)
@dish_ingredient_8 = create(:dish_ingredient, dish: @dish_3, ingredient: @ingredient_4)
@dish_ingredient_9 = create(:dish_ingredient, dish: @dish_3, ingredient: @ingredient_5)
@dish_ingredient_10 = create(:dish_ingredient, dish: @dish_4, ingredient: @ingredient_4)
@dish_ingredient_11 = create(:dish_ingredient, dish: @dish_4, ingredient: @ingredient_5)
@dish_ingredient_12 = create(:dish_ingredient, dish: @dish_4, ingredient: @ingredient_6)
@dish_ingredient_13 = create(:dish_ingredient, dish: @dish_5, ingredient: @ingredient_5)
@dish_ingredient_14 = create(:dish_ingredient, dish: @dish_5, ingredient: @ingredient_6)
@dish_ingredient_15 = create(:dish_ingredient, dish: @dish_5, ingredient: @ingredient_7)
@dish_ingredient_16 = create(:dish_ingredient, dish: @dish_6, ingredient: @ingredient_6)
@dish_ingredient_17 = create(:dish_ingredient, dish: @dish_6, ingredient: @ingredient_7)
@dish_ingredient_18 = create(:dish_ingredient, dish: @dish_6, ingredient: @ingredient_8)
@dish_ingredient_19 = create(:dish_ingredient, dish: @dish_7, ingredient: @ingredient_7)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_7, ingredient: @ingredient_8)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_7, ingredient: @ingredient_9)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_8, ingredient: @ingredient_8)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_8, ingredient: @ingredient_9)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_8, ingredient: @ingredient_10)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_9, ingredient: @ingredient_9)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_9, ingredient: @ingredient_10)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_9, ingredient: @ingredient_11)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_10, ingredient: @ingredient_10)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_10, ingredient: @ingredient_11)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_10, ingredient: @ingredient_12)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_11, ingredient: @ingredient_11)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_11, ingredient: @ingredient_12)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_11, ingredient: @ingredient_13)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_12, ingredient: @ingredient_12)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_12, ingredient: @ingredient_13)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_12, ingredient: @ingredient_14)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_13, ingredient: @ingredient_13)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_13, ingredient: @ingredient_14)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_13, ingredient: @ingredient_15)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_14, ingredient: @ingredient_14)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_14, ingredient: @ingredient_15)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_14, ingredient: @ingredient_1)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_15, ingredient: @ingredient_15)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_15, ingredient: @ingredient_1)
@dish_ingredient_20 = create(:dish_ingredient, dish: @dish_15, ingredient: @ingredient_2)
