# Generated by Django 4.2.3 on 2023-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='lore',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default='', max_length=250),
        ),
    ]
