# Generated by Django 4.2.3 on 2023-08-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_imgs_alter_event_lore_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.TextField(default='none'),
        ),
    ]
