# Generated by Django 4.2.4 on 2023-08-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
